### ISSUE TITLE
仿微信密码输入框，需要考虑边框的线宽

### ISSUE THREAD

**Issue by dxy1046** [lygttpod/AndroidCustomView#12]
背景的圆角矩形，如果按照现有代码绘制，圆角矩形的线宽只是设定值的一半，
rectF.set(0,0,width,height);应改为
rectF.set(borderLineWidth * 1f / 2, borderLineWidth * 1f / 2, width - borderLineWidth * 1f / 2, height - borderLineWidth * 1f / 2);
borderLineWidth为圆角矩形线宽值

**Comment by lygttpod** [comment]
是的，精确的计算是要算上画笔的线宽
