### ISSUE TITLE
大佬，遇到一个问题，顶部的外框线没了

### ISSUE THREAD

**Issue by JMaKing** [lygttpod/AndroidCustomView#13]
<img width="288" alt="屏幕快照 2019-03-23 下午5 14 49" src="https://user-images.githubusercontent.com/26948872/54864233-66b04180-4d8f-11e9-98de-bd3690e9788d.png">

**Comment by JMaKing** [comment]
我找到原因了，高度写成40dp就回这样了，有个阀值- -，具体没试，50dp是可以的，看来还要再改改- -

**Comment by lygttpod** [comment]
EditText自己有个内容最小高度，低于这个高度他是可以上下滚动显示内容的
