### ISSUE TITLE
int baseline = (textRect.bottom + textRect.top - fontMetrics.bottom - fontMetrics.top) / 2;这个为啥是必须要除以2

### ISSUE THREAD

**Issue by willBars** [lygttpod/AndroidCustomView#3]
您好,
看了你写的这个受益颇多,自己动手写了一遍,有点疑惑的地方,就是在绘制文本的时候,cancas.drawText(string,int,int,paint)时,传入的第三个参数时,其int end的值为啥要除以2,而且除以其他数字的值都不可以!
烦请答疑解惑!谢谢

**Comment by lygttpod** [comment]
@willBars 
FontMetrics.top的数值是个负数，其绝对值就是字体绘制边界到baseline的距离。
所以如果是把文字画在 FontMetrics高度的矩形中， drawText就应该传入 -FontMetrics.top。
要画在targetRect的居中位置，baseline的计算公式就是：
targetRect.centerY() - (FontMetrics.bottom - FontMetrics.top) / 2 - FontMetrics.top
优化后即：

(targetRect.bottom + targetRect.top - fontMetrics.bottom - fontMetrics.top) / 2


给你个链接看看相关介绍 [链接](http://blog.csdn.net/hursing/article/details/18703599)

**Comment by lygttpod** [comment]
@willBars 今天提供了一种新的思路处理，你可以看下源码哦
