### ISSUE TITLE
TextView实现打印机效果的问题

### ISSUE THREAD

**Issue by SkyShiYan** [lygttpod/AndroidCustomView#5]
当设备的cpu不是特别好，获取cpu比较忙的时，修改显示的duration果断，会有字不显示的问题。

**Comment by lygttpod** [comment]
@SkyShiYan 我这边试了下  正常机型没遇到问题，模拟器跑起来也没有出现不显示的问题，方便的话发个gif图或者搞个小视频发我邮箱看下
