### ISSUE TITLE
textview打印机。

### ISSUE THREAD

**Issue by Xiaocai9527** [lygttpod/AndroidCustomView#7]
textview自带append方法；

//直接用这个貌似更好点
                    append(arr[index]);
//                    stringBuffer.append(arr[index]);
                    currentIndex = index;
                    //所有文字都显示完成之后进度回调结束动画
                    if (currentIndex == (textCount - 1))
                    {
                        if (textAnimationListener != null)
                        {
                            textAnimationListener.animationFinish();
                        }
                    }

                    //新思路的做法
//                    setText(stringBuffer.toString());

                    /**
                     * 之前的做法刷新重绘text,需要自己控制文字的绘制，
                     * 看到网友的评论开拓了思路，既然是直接集成TextView
                     * 就可以直接使用setText()方法进行设置值了
                     */
                    //invalidate();老思路的做法

**Comment by lygttpod** [comment]
不错的思路 👍👍👍
