### ISSUE TITLE
自定义密码框有个bug

### ISSUE THREAD

**Issue by FrankLove** [lygttpod/AndroidCustomView#9]
控件宽度入设置wrap_content的话那么就看不见输入框了
 <com.demoapplication.view.PayPsdInputView
        android:id="@+id/editText"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:inputType="number"
        app:maxCount="6"
        app:psdType="weChat"
        app:rectAngle="5dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/titile" />

**Comment by lygttpod** [comment]
因为每个小的输入区域是根据view宽度计算得出来的，所以宽度不支持wrap_content，否则无法进行计算
